name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup mkosi
        uses: systemd/mkosi@v19
      - name: Build Image
        run: mkosi
